gui: Export DISPLAY and XAUTHORITY
In Ubuntu 14.04 with MATE (possibly others),
not exporting DISPLAY and XAUTHORITY causes GameConqueror to fail
loading with errors like:
   error: XDG_RUNTIME_DIR not set in the environment
    (GameConqueror.py:4181): Gtk-CRITICAL **:
      gtk_clipboard_get_for_display:
        assertion 'display != NULL' failed

So always export DISPLAY and XAUTHORITY.