gui: use split() instead of strip() in data_worker
With Python 3 the following backtrace is triggered. It seems like
Python 3 doesn't like that there are further chars besides spaces
in the string. So split at spaces and only use the first part.

Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 939, in data_worker
    new_value = self.read_value(addr, TYPENAMES_S2G[scanmem_type.strip()], cur_value)
KeyError: 'I32 ]\\n'

Fixes: GitHub issue #77 "GUI won't start"