gui: fix a hang when searching in scan results
Commit aedf0695b899 ("gui: add match offset and region type support")
doesn't handle the match offset and region type when searching in
the scan results which causes GameConqueror to hang and to output a
backtrace. So handle them there as well.

Traceback (most recent call last):
  File "/usr/share/gameconqueror/GameConqueror.py", line 936, in data_worker
    addr, cur_value, scanmem_type, valid = row
ValueError: too many values to unpack

Fixes: aedf0695b899 ("gui: add match offset and region type support")